from app.models.team import Team
from app.models.game import Game
from app.models.odds import Odds
from app.models.prediction_output import PredictionOutput
from app.models.schema_deprecation import SchemaDeprecation
from app.models.nik_score import NikScore
from app.models.prediction_outcome import PredictionOutcome
from app.models.prediction_result import PredictionResult
from app.models.prediction_evaluation import PredictionEvaluation
from app.models.prediction_snapshot import PredictionSnapshot
from app.models.analytics_feature import AnalyticsFeature
from app.models.team_performance import TeamPerformance
from app.models.backtest_result import BacktestResult
from app.models.model_performance import ModelPerformance
from app.models.feature_snapshot import FeatureSnapshot
from app.models.job_execution import JobExecution
from app.models.user import User
from app.models.password_reset_token import PasswordResetToken
from app.models.recovery_email_verification import RecoveryEmailVerification
from app.models.forgot_email_challenge import ForgotEmailChallenge
from app.models.weight_profile import WeightProfile
from app.models.market_value import MarketValue
from app.models.betting_recommendation import BettingRecommendation
from app.models.bankroll import Bankroll
from app.models.bet_portfolio import BetPortfolio
from app.models.parlay import Parlay
from app.models.live_game import LiveGame
from app.models.feature_candidate import FeatureCandidate
from app.models.model_experiment import ModelExperiment
from app.models.ensemble_prediction import EnsemblePrediction
from app.models.prediction_history import PredictionHistory
from app.models.user_profile import UserProfile
from app.models.betting_preferences import BettingPreferences
from app.models.user_feedback import UserFeedback
from app.models.user_strategy import UserStrategy
from app.models.coach_conversation import CoachConversation
from app.models.user_bet import UserBet
from app.models.sportsbook_odds import SportsbookOdds
from app.models.sport_configuration import SportConfiguration
from app.models.live_game_state import LiveGameState
from app.models.game_event import GameEvent
from app.models.community_profile import CommunityProfile
from app.models.user_follow import UserFollow
from app.models.shared_strategy import SharedStrategy
from app.models.community_prediction import CommunityPrediction
from app.models.discussion import Discussion
from app.models.pipeline_run import PipelineRun
from app.models.prediction_record import Prediction
from app.models.ai_analysis import AIAnalysis
