"""add nik score confidence fields

Revision ID: 2562cf636fc8
Revises: b0d08ae55de7
Create Date: 2026-07-22 10:36:47.648964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2562cf636fc8'
down_revision: Union[str, Sequence[str], None] = 'b0d08ae55de7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nik_scores', sa.Column('confidence_level', sa.String(), nullable=True))
    op.add_column('nik_scores', sa.Column('model_version', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nik_scores', 'model_version')
    op.drop_column('nik_scores', 'confidence_level')
    # ### end Alembic commands ###
