"""add team performance features

Revision ID: 430e72276f2a
Revises: 6011ffeb7a71
Create Date: 2026-07-22 08:24:52.789962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '430e72276f2a'
down_revision: Union[str, Sequence[str], None] = '6011ffeb7a71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('win_percentage', sa.Float(), nullable=True),
    sa.Column('avg_points_for', sa.Float(), nullable=True),
    sa.Column('avg_points_against', sa.Float(), nullable=True),
    sa.Column('home_win_percentage', sa.Float(), nullable=True),
    sa.Column('away_win_percentage', sa.Float(), nullable=True),
    sa.Column('current_streak', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_performance')
    # ### end Alembic commands ###
