"""create analytics features table

Revision ID: 6011ffeb7a71
Revises: 39b705f4d87c
Create Date: 2026-07-21 22:12:08.638101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6011ffeb7a71'
down_revision: Union[str, Sequence[str], None] = '39b705f4d87c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('home_rest_days', sa.Integer(), nullable=True),
    sa.Column('away_rest_days', sa.Integer(), nullable=True),
    sa.Column('line_movement', sa.Float(), nullable=True),
    sa.Column('implied_home_probability', sa.Float(), nullable=True),
    sa.Column('implied_away_probability', sa.Float(), nullable=True),
    sa.Column('favorite_is_home', sa.Boolean(), nullable=True),
    sa.Column('home_back_to_back', sa.Boolean(), nullable=True),
    sa.Column('away_back_to_back', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analytics_features')
    # ### end Alembic commands ###
