"""add database performance indexes

Revision ID: 8eb5149a9962
Revises: ad73f47baf22
Create Date: 2026-07-23 03:47:24.807382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eb5149a9962'
down_revision: Union[str, Sequence[str], None] = 'ad73f47baf22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    def create_index_if_missing(index_name: str, table_name: str, columns: list[str]) -> None:
        existing = {index['name'] for index in inspector.get_indexes(table_name)}
        if index_name not in existing:
            op.create_index(index_name, table_name, columns, unique=False)

    create_index_if_missing('idx_game_sport_date', 'games', ['sport', 'game_date'])
    create_index_if_missing('idx_game_teams', 'games', ['home_team_id', 'away_team_id'])
    create_index_if_missing('idx_evaluation_correct', 'prediction_evaluations', ['correct'])
    create_index_if_missing('idx_evaluation_snapshot', 'prediction_evaluations', ['snapshot_id'])
    create_index_if_missing('idx_snapshot_game', 'prediction_snapshots', ['game_id'])
    create_index_if_missing('idx_snapshot_model', 'prediction_snapshots', ['model_version'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_snapshot_model', table_name='prediction_snapshots')
    op.drop_index('idx_snapshot_game', table_name='prediction_snapshots')
    op.drop_index('idx_evaluation_snapshot', table_name='prediction_evaluations')
    op.drop_index('idx_evaluation_correct', table_name='prediction_evaluations')
    op.drop_index('idx_game_teams', table_name='games')
    op.drop_index('idx_game_sport_date', table_name='games')
    # ### end Alembic commands ###
