"""add predictive performance features

Revision ID: b0820a3ff5dd
Revises: 0249a31c1dbc
Create Date: 2026-07-22 19:15:22.165326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0820a3ff5dd'
down_revision: Union[str, Sequence[str], None] = '0249a31c1dbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_performance', sa.Column('points_for_avg', sa.Float(), nullable=True))
    op.add_column('team_performance', sa.Column('points_against_avg', sa.Float(), nullable=True))
    op.add_column('team_performance', sa.Column('recent_form', sa.Float(), nullable=True))
    op.add_column('team_performance', sa.Column('home_record', sa.Float(), nullable=True))
    op.add_column('team_performance', sa.Column('away_record', sa.Float(), nullable=True))
    op.add_column('team_performance', sa.Column('offensive_rating', sa.Float(), nullable=True))
    op.add_column('team_performance', sa.Column('defensive_rating', sa.Float(), nullable=True))
    op.drop_column('team_performance', 'win_percentage')
    op.drop_column('team_performance', 'home_win_percentage')
    op.drop_column('team_performance', 'avg_points_for')
    op.drop_column('team_performance', 'avg_points_against')
    op.drop_column('team_performance', 'away_win_percentage')
    op.drop_column('team_performance', 'current_streak')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_performance', sa.Column('current_streak', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('team_performance', sa.Column('away_win_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('team_performance', sa.Column('avg_points_against', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('team_performance', sa.Column('avg_points_for', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('team_performance', sa.Column('home_win_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('team_performance', sa.Column('win_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('team_performance', 'defensive_rating')
    op.drop_column('team_performance', 'offensive_rating')
    op.drop_column('team_performance', 'away_record')
    op.drop_column('team_performance', 'home_record')
    op.drop_column('team_performance', 'recent_form')
    op.drop_column('team_performance', 'points_against_avg')
    op.drop_column('team_performance', 'points_for_avg')
    # ### end Alembic commands ###
